version: '3.8'

services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=docker
      - CI=true
      - BASE_URL=http://localhost:3000/
      - HEADLESS=true
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
    ports:
      - "9000:3000"
    depends_on:
      - web-app

  web-app:
    image: node:20-slim
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
    command: npm run dev
    volumes:
      - ./:/app

volumes:
  reports:
  logs:
